### ISSUE TITLE
I need some help implementing this in my project

### ISSUE THREAD

**Issue by leossmith** [distriqt/ANE-IronSource#11]
I have followed the guides to implement this ANE but without any luck. I have added the needed ANEs in my project (core, ironsource, playservices.ads, playservices.base and androidsupport.v4).

My project in Ironsrc is enabled and banner and interstitial are live. 

My code on start:

```

						IronSource.instance.init( IRONSRC_APP_KEY);
						if (IronSource.isSupported)
						{
							IronSource.instance.loadInterstitial();
							IronSource.instance.validateIntegration();
							IronSource.instance.addEventListener("onBannerAdLoaded", onBannerAdLoaded);
							IronSource.instance.addEventListener("onBannerAdLoadFailed", onBannerAdLoadFailed);
							IronSource.instance.addEventListener("onBannerAdClicked", onBannerAdClicked);
							IronSource.instance.addEventListener("onBannerAdScreenPresented", onBannerAdScreenPresented);
							IronSource.instance.addEventListener("onBannerAdScreenDismissed", onBannerAdScreenDismissed);
							IronSource.instance.addEventListener("onBannerAdLeftApplication", onBannerAdLeftApplication);
							
							IronSource.instance.loadInterstitial();
						}



```

Do you have any ideas what might be wrong?

##### Expected behaviour
Banner and interstitial should appear when they load. ValidateIntegration doesn't trace any info in the console. 

##### Actual behaviour
Nothing happens

##### Environment 

- AIR SDK version: 32 latest
- Device OS: Android 9
- Device version: oneplus 6t latest version
- Development IDE: Flash Builder 4.7 or intellij
- Development OS: windows 10 64

**Comment by marchbold** [comment]
When you call init you'll need to enable interstitial ad units:

```as3
IronSource.instance.init( IRONSRC_APP_KEY, [ IronSource.INTERSTITIAL ] );
```

This mimics the call in the native SDK:

- https://developers.ironsrc.com/ironsource-mobile/android/android-sdk/#step-5
- https://developers.ironsrc.com/ironsource-mobile/ios/ios-sdk/#step-3

---

The call to `validateIntegration()` outputs to the native device log, you will need to be following it to see the output:

https://airnativeextensions.github.io/tutorials/device-logs

**Comment by leossmith** [comment]
I have tried with adding type of ad units in init but it doesn't make any difference. I am adding some logs, if they make any sense.

```
11-08 13:49:34.821  6382  6382 W System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
11-08 13:49:34.821  6382  6382 W System.err:    at android.app.ContextImpl.checkMode(ContextImpl.java:2544)
11-08 13:49:34.822  6382  6382 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:417)
11-08 13:49:34.822  6382  6382 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:407)
11-08 13:49:34.822  6382  6382 W System.err:    at com.adobe.air.AIRSharedPref.getConfigData(AIRSharedPref.java:113)
11-08 13:49:34.822  6382  6382 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-08 13:49:34.822  6382  6382 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-08 13:49:34.822  6382  6382 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-08 13:49:34.822  6382  6382 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-08 13:49:34.822  6382  6382 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:792)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2675)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1637)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7797)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:984)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:809)
11-08 13:49:34.822  6382  6382 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
11-08 13:49:34.822  6382  6382 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
11-08 13:49:34.822  6382  6382 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-08 13:49:34.822  6382  6382 W System.err:    at android.os.Looper.loop(Looper.java:193)
11-08 13:49:34.822  6382  6382 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6898)
11-08 13:49:34.822  6382  6382 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-08 13:49:34.822  6382  6382 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
11-08 13:49:34.822  6382  6382 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-08 13:49:34.831  6382  6382 W System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ContextImpl.checkMode(ContextImpl.java:2544)
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:417)
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:407)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AIRSharedPref.getConfigRequestTime(AIRSharedPref.java:70)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:792)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2675)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1637)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7797)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:984)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:809)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
11-08 13:49:34.831  6382  6382 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
11-08 13:49:34.831  6382  6382 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-08 13:49:34.831  6382  6382 W System.err:    at android.os.Looper.loop(Looper.java:193)
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6898)
11-08 13:49:34.831  6382  6382 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-08 13:49:34.831  6382  6382 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
11-08 13:49:34.831  6382  6382 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-08 13:49:34.831  6382  6382 W System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ContextImpl.checkMode(ContextImpl.java:2544)
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:417)
11-08 13:49:34.831  6382  6382 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:407)
11-08 13:49:34.831  6382  6382 W System.err:    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AIRSharedPref.setConfigRequestTime(AIRSharedPref.java:148)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-08 13:49:34.831  6382  6382 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:792)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2675)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1637)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7797)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:984)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:809)
11-08 13:49:34.831  6382  6382 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
11-08 13:49:34.831  6382  6382 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
11-08 13:49:34.831  6382  6382 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-08 13:49:34.831  6382  6382 W System.err:    at android.os.Looper.loop(Looper.java:193)
11-08 13:49:34.832  6382  6382 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6898)
11-08 13:49:34.832  6382  6382 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-08 13:49:34.832  6382  6382 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
11-08 13:49:34.832  6382  6382 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-08 13:49:36.294  6382  6382 D com.distriqt.IronSource: IronSourceController::getAdvertiserId()
11-08 13:49:36.299  6382  6382 D com.distriqt.IronSource: IronSourceController::init( 696e059d, [rewardedvideo,interstitial] )
11-08 13:49:36.333  6382  6382 D com.distriqt.IronSource: IronSourceController::validateIntegration()
11-08 13:49:36.341  6382  6382 D com.distriqt.IronSource: IronSourceController::loadInterstitial()
11-08 13:49:36.342  6382  6382 D com.distriqt.IronSource: IronSourceController::showRewardedVideo( DefaultRewardedVideo )
11-08 13:49:36.342  6382  6382 D com.distriqt.IronSource: IronSourceController::getAdvertiserId()
11-08 13:49:36.343  6382  6467 D com.distriqt.IronSource: IronSourceController::onRewardedVideoAdShowFailed()
11-08 13:49:37.239  6382  6467 D com.distriqt.IronSource: IronSourceController::onRewardedVideoAvailabilityChanged()
11-08 13:49:37.239  6382  6477 D com.distriqt.IronSource: IronSourceController::onInterstitialAdReady()
11-08 13:49:37.242  6382  6382 D com.distriqt.IronSource: IronSourceController::showInterstitial( DefaultInterstitial )
11-08 13:49:37.242  6382  6467 D com.distriqt.IronSource: IronSourceController::onInterstitialAdShowFailed()
11-08 13:49:44.617  6382  6382 D com.distriqt.IronSource: IronSourceController::loadInterstitial()
11-08 13:49:44.617  6382  6382 D com.distriqt.IronSource: IronSourceController::onInterstitialAdReady()
11-08 13:49:44.620  6382  6382 D com.distriqt.IronSource: IronSourceController::showInterstitial( DefaultInterstitial )
11-08 13:49:44.621  6382  6467 D com.distriqt.IronSource: IronSourceController::onInterstitialAdShowFailed()
11-08 13:49:47.922  6382  6382 D com.distriqt.IronSource: IronSourceController::loadInterstitial()
11-08 13:49:47.923  6382  6382 D com.distriqt.IronSource: IronSourceController::onInterstitialAdReady()
11-08 13:49:47.926  6382  6382 D com.distriqt.IronSource: IronSourceController::showInterstitial( DefaultInterstitial )
11-08 13:49:47.927  6382  6467 D com.distriqt.IronSource: IronSourceController::onInterstitialAdShowFailed()
11-08 13:49:48.695  6382  6382 D com.distriqt.IronSource: IronSourceController::showInterstitial( 1067815 )
11-08 13:49:48.696  6382  6467 D com.distriqt.IronSource: IronSourceController::onInterstitialAdShowFailed()

```

**Comment by marchbold** [comment]
Can you post the full log? Looks like the ads are failing to show, could be because of an account issue?

Also you could try with no placement string, see if that makes a difference.

**Comment by leossmith** [comment]
I have contacted ironsource to check if there is an issue with the account.

**Comment by leossmith** [comment]
Ok so it looks like something was wrong with Ironsource and not the implementation. After contacting them, they enabled something and now it works. 

Sadly if your account doesn't work, there is nothing to identify it.

ps. Although this works, wiki needs update as I think it misses the use of .ads and .base.

**Comment by marchbold** [comment]
Glad to hear you got it working.

Are you referring to Google Play Services ANEs ? Definitely seem to be missing from the docs. I'll get them added.

**Comment by leossmith** [comment]
Yes, I am referring to Google Play Services. Although they can be found in the example, there is no link or reference in the Wiki, which can be confusing. Also there is a link from wiki to the website, which goes to 404.

**Comment by marchbold** [comment]
Yeah we actually hadn't written any wiki docs for this one yet. Was just an internal ANE that we pushed live, but probably should have prepped it a bit more. I've put up some better docs now and will correct the 404 later today.

**Comment by walddada** [comment]
please I need your help
