### ISSUE TITLE
Android AdMob crashes

### ISSUE THREAD

**Issue by ichark** [distriqt/ANE-IronSource#38]
Huge count of the same crashes in AdMob library. 

##### Android 11, Android 12

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/appset/AppSet;
       at com.google.android.gms.internal.ads.zzfda.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcro.zzd(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcrl.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
       
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/appset/AppSet;
       at com.google.android.gms.internal.ads.zzfda.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzfda.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzeot.zzb(com.google.android.gms:play-services-ads@@21.0.0:13)
       at com.google.android.gms.internal.ads.zzete.zza(com.google.android.gms:play-services-ads@@21.0.0:4)
       at com.google.android.gms.internal.ads.zzday.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzday.zzc(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcyz.zzi(com.google.android.gms:play-services-ads@@21.0.0:4)
       at com.google.android.gms.internal.ads.zzexq.zzb(com.google.android.gms:play-services-ads@@21.0.0:49)
       at com.google.android.gms.internal.ads.zzelj.zzf(com.google.android.gms:play-services-ads@@21.0.0:5)
       at com.google.android.gms.internal.ads.zzelj.zzaa(com.google.android.gms:play-services-ads@@21.0.0:2)
       at com.google.android.gms.ads.internal.client.zzdu.zzm(com.google.android.gms:play-services-ads-lite@@21.0.0:26)
       at com.google.android.gms.ads.BaseAdView.loadAd(com.google.android.gms:play-services-ads-lite@@21.0.0:5)
       at com.ironsource.adapters.admob.AdMobAdapter$10.run(AdMobAdapter.java:584)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 
 Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/appset/AppSet;
       at com.google.android.gms.internal.ads.zzeot.<init>(com.google.android.gms:play-services-ads@@21.0.0:3)
       at com.google.android.gms.internal.ads.zzeov.zzb(com.google.android.gms:play-services-ads@@21.0.0:4)
       at com.google.android.gms.internal.ads.zzgqf.zzc(com.google.android.gms:play-services-ads@@21.0.0:9)
       at com.google.android.gms.internal.ads.zzetf.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzdaz.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzedz.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzedq.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzedg.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgqf.zzc(com.google.android.gms:play-services-ads@@21.0.0:9)
       at com.google.android.gms.internal.ads.zzdhf.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzeir.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcza.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcph.zzd(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzexq.zzb(com.google.android.gms:play-services-ads@@21.0.0:49)
       at com.google.android.gms.internal.ads.zzelj.zzf(com.google.android.gms:play-services-ads@@21.0.0:5)
       at com.google.android.gms.internal.ads.zzelj.zzaa(com.google.android.gms:play-services-ads@@21.0.0:2)
       at com.google.android.gms.ads.internal.client.zzdu.zzm(com.google.android.gms:play-services-ads-lite@@21.0.0:26)
       at com.google.android.gms.ads.BaseAdView.loadAd(com.google.android.gms:play-services-ads-lite@@21.0.0:5)
       at com.ironsource.adapters.admob.AdMobAdapter$10.run(AdMobAdapter.java:467)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                   

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/appset/AppSet;
       at com.google.android.gms.internal.ads.zzeot.<init>(com.google.android.gms:play-services-ads@@21.0.0:3)
       at com.google.android.gms.internal.ads.zzeov.zzb(com.google.android.gms:play-services-ads@@21.0.0:4)
       at com.google.android.gms.internal.ads.zzgqf.zzc(com.google.android.gms:play-services-ads@@21.0.0:9)
       at com.google.android.gms.internal.ads.zzetf.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzdaz.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzedz.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzedq.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzedg.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgqf.zzc(com.google.android.gms:play-services-ads@@21.0.0:9)
       at com.google.android.gms.internal.ads.zzdhf.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzeir.zza(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcza.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzgpt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcqt.zzb(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzeyk.zzb(com.google.android.gms:play-services-ads@@21.0.0:2)
       at com.google.android.gms.internal.ads.zzeyk.zzc(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzfat.zzb(com.google.android.gms:play-services-ads@@21.0.0:19)
       at com.google.android.gms.internal.ads.zzfax.zzt(com.google.android.gms:play-services-ads@@21.0.0:10)
       at com.google.android.gms.internal.ads.zzfax.zzf(com.google.android.gms:play-services-ads@@21.0.0:1)
       at com.google.android.gms.internal.ads.zzcbm.zza(com.google.android.gms:play-services-ads-lite@@21.0.0:2)
       at com.google.android.gms.ads.rewarded.RewardedAd.load(com.google.android.gms:play-services-ads-lite@@21.0.0:12)
       at com.ironsource.adapters.admob.AdMobAdapter.loadRewardedVideoAdFromAdMob(AdMobAdapter.java:320)
       at com.ironsource.adapters.admob.AdMobAdapter.onNetworkInitCallbackSuccess(AdMobAdapter.java:742)
       at com.ironsource.adapters.admob.AdMobAdapter.initializationSuccess(AdMobAdapter.java:711)
       at com.ironsource.adapters.admob.AdMobAdapter.initSDK(AdMobAdapter.java:203)
       at com.ironsource.adapters.admob.AdMobAdapter.access$300(AdMobAdapter.java:55)
       at com.ironsource.adapters.admob.AdMobAdapter$3.run(AdMobAdapter.java:264)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by marchbold** [comment]
Try adding the `com.distriqt.playservices.AppSet` extension to your app. Available here: https://github.com/distriqt/ANE-GooglePlayServices

or 

```
apm install com.distriqt.playservices.AppSet
```

**Comment by ichark** [comment]
Thanks  we will try.

**Comment by marchbold** [comment]
Cheers, let me know how it goes. I'll make sure we get this additional dependency corrected in the docs and airpackage.
