### ISSUE TITLE
Banners not loading - FRENoSuchNameException

### ISSUE THREAD

**Issue by mrfrasier** [distriqt/ANE-IronSource#55]
On iOS, banners load no issue. On Android, even with a stripped-down setup (nothing but IronSource, no other adapters) no banners load. Interstitials load, but no banners.

##### Environment 

Windows 11, Adobe AIR 50.2.3.6, latest IronSource ANE via APM

##### Logs

```
com.adobe.fre.FRENoSuchNameException
at com.adobe.fre.FREObject.getProperty(Native Method)
at com.distriqt.extension.ironsource.functions.banners.LoadBannerFunction.call(LoadBannerFunction.java:37)
at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
at com.adobe.air.customHandler.handleMessage(customHandler.java:33)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by mrfrasier** [comment]
Additional information: I was on version 3.9.0 (latest). I uninstalled it via apm, then ran "apm install com.distriqt.IronSource 3.7.4" to get the previous release. This release shows banners, so it seems there's an issue with banners on Android in 3.9.0 -- that or I'm doing something wrong because it's odd no one else would report it.

**Comment by marchbold** [comment]
Could you try this build for me: 

https://drive.google.com/file/d/1ikI14vwnz6PiugsCaOwV5SuUP3p5Oqde/view?usp=sharing

**Comment by mrfrasier** [comment]
> Could you try this build for me:
> 
> https://drive.google.com/file/d/1ikI14vwnz6PiugsCaOwV5SuUP3p5Oqde/view?usp=sharing

Banner ads do indeed work with this build! I assume I can use it with the latest adapters as well? Seems things auto update when I touch a related package

**Comment by marchbold** [comment]
Yes this has the same version of the ironsource sdk so will work with the current mediators. I'll get this update rolled out today.
